# Generated by Django 5.1.1 on 2024-11-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('p_price', models.CharField(max_length=20)),
                ('p_discount', models.CharField(max_length=20)),
                ('p_photo', models.ImageField(default='default.jpg', upload_to='')),
                ('p_detail', models.CharField(max_length=1000)),
            ],
        ),
    ]
