# Generated by Django 4.2.16 on 2024-11-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_name', models.CharField(max_length=100)),
                ('o_price', models.CharField(max_length=20)),
                ('o_discount', models.CharField(max_length=20)),
                ('o_photo', models.ImageField(default='default.jpg', upload_to='')),
            ],
        ),
    ]
