# Generated by Django 4.2.16 on 2024-11-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='delevary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dm_name', models.CharField(max_length=100)),
                ('dm_location', models.CharField(max_length=100)),
                ('dm_number', models.CharField(max_length=100)),
                ('dm_others', models.CharField(max_length=100)),
                ('dm_photo', models.ImageField(default='default.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ordersnew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_name', models.CharField(max_length=100)),
                ('o_photo', models.ImageField(default='default.jpg', upload_to='')),
                ('o_location', models.CharField(max_length=100)),
                ('o_number', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='productsnew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('p_photo', models.ImageField(default='default.jpg', upload_to='')),
                ('p_detail', models.CharField(max_length=1000)),
                ('p_others', models.CharField(max_length=100)),
            ],
        ),
    ]
