# Generated by Django 4.2.16 on 2024-11-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delevary_ordersnew_productsnew'),
    ]

    operations = [
        migrations.CreateModel(
            name='products1223432123',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=1200)),
            ],
        ),
    ]
