# Generated by Django 4.2.16 on 2024-12-13 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_category_description_comments_comments_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comments',
            new_name='commentbox',
        ),
    ]
